// Educational PoC stub generated by SolGuardian for a Solana / Anchor finding.
// Runs against the synthetic sample program only. No mainnet interaction.
//
// Finding : {{FINDING_ID}} - {{TITLE}}
// Severity: {{SEVERITY}} (confidence {{CONFIDENCE}})
// Rule    : {{RULE}}
// Skill   : {{SKILL}}
// Location: {{LOCATION}}
//
// Setup:
//   cargo new poc-harness --lib   # or use the sample's Anchor workspace
//   add dev-dependencies: solana-program-test = "1.18", tokio = { version = "1", features = ["macros"] }
//   cargo test --features test-suites {{TEST_NAME}}

#![cfg(feature = "test-suites")]

use anchor_lang::prelude::*;
use solana_program_test::{processor, tokio, ProgramTest, ProgramBanks};

// TODO: import the sample program under test, e.g.
// use vault::instruction::{ {{FUNCTION}} };
// use vault::{Accounts, {{ACCOUNTS_STRUCT}}};

/// PoC harness for {{FINDING_ID}} - {{TITLE}}
#[tokio::test]
async fn {{TEST_NAME}}() {
    // -- Arrange -------------------------------------------------------------
    // Step 1 - {{EXPLOIT_STEP_1}}
    // Step 2 - {{EXPLOIT_STEP_2}}
    // Step 3 - {{EXPLOIT_STEP_3}}
    //
    // let mut program_test = ProgramTest::new("vault", vault::ID, None);
    // program_test.add_program(...);
    // let (banks_client, payer, blockhash) = program_test.start().await;

    // -- Act -----------------------------------------------------------------
    // Build the instruction that omits the validation SolGuardian flagged, e.g.
    // pass an unsigned / wrong-owner account, or a foreign CPI program id.

    // -- Assert --------------------------------------------------------------
    // The vulnerable build accepts the instruction:
    // assert!(result.is_ok(), "expected the buggy path to succeed (proves the gap)");
    panic!(
        "PoC stub for {{FINDING_ID}}: wire the instruction builder above. \
         SolGuardian emits skeletons, not weapons."
    );
}

/// Control test: after the patch the same instruction must fail with the account
/// validation error.
#[tokio::test]
async fn {{TEST_NAME}}_after_patch_fails() {
    // Patch sketch from the finding:
    //   {{PATCH_1}}
    //   {{PATCH_2}}
    panic!("implement once the fix lands: expect Err(ProgramError::MissingRequiredSignature)");
}
