// SPDX-License-Identifier: MIT
// Educational PoC stub generated by SolGuardian. Target: synthetic samples only.
// This is a skeleton: it names the vulnerable function and the shape of the attack,
// but contains no live mainnet exploit path. Run it against the sample contract in a
// local Foundry fork/anvil sandbox, never against deployed funds.
//
// Finding : {{FINDING_ID}} - {{TITLE}}
// Severity: {{SEVERITY}} (confidence {{CONFIDENCE}})
// Rule    : {{RULE}}
// Skill   : {{SKILL}}
// Location: {{LOCATION}}
//
// Setup:
//   forge init poc-harness && cp -r samples/solidity .
//   forge test --match-contract {{HARNESS}} -vvvv

pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../../samples/solidity/{{TARGET_CONTRACT_FILE}}";

/// @title {{HARNESS}}
/// @notice PoC harness for {{FINDING_ID}}.
contract {{HARNESS}} is Test {
    {{TARGET_CONTRACT}} internal target;
    address internal attacker;
    uint256 internal constant SEED_ETH = 2 ether;

    function setUp() public {
        target = new {{TARGET_CONTRACT}}();
        attacker = makeAddr("attacker");
        vm.deal(attacker, SEED_ETH);
        // TODO: fund / seed the vault so the vulnerable path is reachable
    }

    /// @notice {{TITLE}}
    function test_{{TEST_NAME}}() public {
        // Step 1 - attacker reaches the vulnerable entry point:
        //   {{EXPLOIT_STEP_1}}
        // Step 2 - {{EXPLOIT_STEP_2}}
        // Step 3 - {{EXPLOIT_STEP_3}}

        vm.prank(attacker);
        // TODO: call {{TARGET_CONTRACT}}.{{FUNCTION}}(...) with attacker-controlled args.

        // Assertion that proves the bug (fails once patched):
        // assertGt(attacker.balance, SEED_ETH, "expected value to be drained twice");
        assertTrue(true, "placeholder: wire the real call above");
    }

    /// @notice Control test: the same path must revert / not profit after the fix.
    function test_{{TEST_NAME}}_afterPatch_reverts() public {
        // Patch sketch from the finding:
        //   {{PATCH_1}}
        //   {{PATCH_2}}
        assertTrue(true, "implement once the patch lands");
    }
}
